nsforms:
  - env
  - hostcredentials
  - secrets
config:
  credentials:
    clientId: 'email/chinmaykousik1@gmail.com/test-worker'
    accessToken: 'sQtg16XeQm67brCkRvGcEQC5V6F1QOT3So4fFSZV97Ow'
  engine:           native
  engines:
    native:
      createUser: false
  plugins:
    disabled: []
    artifacts: {}
    livelog: {}
    success: {}
    reboot:
      maxLifeCycle: '96 hours'
      allowTaskReboots: true
    # tasks can never take more than 96 hours (but typically are limited by their own maxRunTime)
    maxruntime:
      maxRunTime: '96 hours'
      perTaskLimit: allow
    watchdog: {}
    logprefix:
      hostname: dummy-worker-*
      workerType: dummy-worker-*
      workerGroup: dummy-worker-*
    env:
      extra:
        PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        # we probably don't need the remainder
        TMPDIR: ./tmp
        SHELL: '/bin/bash'
        LANG: 'en_US.UTF-8'
        LC_ALL: 'en_US.UTF-8'
        XPC_FLAGS: '0x0'
        XPC_SERVICE_NAME: '0'
  queueBaseUrl:     https://queue.taskcluster.net/v1
  worker:
    provisionerId:    test-dummy-provisioner
    workerType :      dummy-worker-50
    workerGroup:      test-dummy-workers
    workerId:         dummy-worker-50
    pollingInterval:  10
    reclaimOffset:    120
    minimumReclaimDelay: 30
    concurrency: 1
  temporaryFolder:  /var/tmp/tc-worker-tmp
  webHookServer:
    provider: webhooktunnel
  minimumDiskSpace:   10000000  # 10 GB
  minimumMemory:      1000000   # 1 GB
  monitor:
    project: test-dummy-worker
    logLevel: info
