// generated by go-import-subtree -- DO NOT EDIT
package main

import _ "github.com/taskcluster/taskcluster-worker/engines/extpoints"
import _ "github.com/taskcluster/taskcluster-worker/engines/mock"
import _ "github.com/taskcluster/taskcluster-worker/plugins/extpoints"
import _ "github.com/taskcluster/taskcluster-worker/plugins/success"
