// generated by go-import-subtree -- DO NOT EDIT
package main

import _ "github.com/taskcluster/taskcluster-worker/engines/docker"
import _ "github.com/taskcluster/taskcluster-worker/engines/enginetest"
import _ "github.com/taskcluster/taskcluster-worker/engines/extpoints"
import _ "github.com/taskcluster/taskcluster-worker/engines/mock"
import _ "github.com/taskcluster/taskcluster-worker/engines/qemu"
import _ "github.com/taskcluster/taskcluster-worker/engines/winnative"
import _ "github.com/taskcluster/taskcluster-worker/plugins/artifacts"
import _ "github.com/taskcluster/taskcluster-worker/plugins/env"
import _ "github.com/taskcluster/taskcluster-worker/plugins/extpoints"
import _ "github.com/taskcluster/taskcluster-worker/plugins/livelog"
import _ "github.com/taskcluster/taskcluster-worker/plugins/plugintest"
import _ "github.com/taskcluster/taskcluster-worker/plugins/success"
import _ "github.com/taskcluster/taskcluster-worker/commands/extpoints"
import _ "github.com/taskcluster/taskcluster-worker/commands/help"
import _ "github.com/taskcluster/taskcluster-worker/commands/work"
