// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package docker

type (
	// Config applicable to docker engine
	Config struct {

		// Root Volume blah blah
		RootVolume string `json:"rootVolume"`
	}
)
