// This file is AUTO-GENERATED by github.com/taskcluster/taskcluster-worker/codegen/schema-gen - do not edit!

package livelog

func ConfigSchema() []byte {
	return []byte(`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "additionalProperties": false,
		  "description": "LiveLog config\n",
		  "properties": {
		    "liveLogExe": {
		      "description": "The executable (.exe file) to run the livelog service\n",
		      "title": "LiveLogExecutable",
		      "type": "string"
		    }
		  },
		  "required": [
		    "liveLogExe"
		  ],
		  "title": "Config",
		  "type": "object"
		}
	`)
}

func NewConfig() *Config {
	return new(Config)
}
