// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package livelog

import "github.com/taskcluster/taskcluster-worker/runtime"

type (
	// LiveLog config
	config struct {

		// The executable (.exe file) to run the livelog service
		LiveLogExe string `json:"liveLogExe"`
	}
)

func configSchema() runtime.CompositeSchema {
	schema, err := runtime.NewCompositeSchema(
		"config",
		`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "additionalProperties": false,
		  "description": "LiveLog config",
		  "properties": {
		    "liveLogExe": {
		      "description": "The executable (.exe file) to run the livelog service",
		      "title": "LiveLogExecutable",
		      "type": "string"
		    }
		  },
		  "required": [
		    "liveLogExe"
		  ],
		  "title": "Config",
		  "type": "object"
		}
		`,
		true,
		func() interface{} {
			return &config{}
		},
	)
	if err != nil {
		panic(err)
	}
	return schema
}
