// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package livelog

type (
	// LiveLog config
	LiveLog struct {

		// The executable (.exe file) to run the livelog service
		LiveLogExe string `json:"liveLogExe"`
	}
)
