$schema:            http://json-schema.org/draft-04/schema#
title:              Config
description: |-
  Config applicable to windows native engine
type:               object
properties:
  accessToken:
    title:          Access Token
    description: |-
      Taskcluster access token used by taskcluster worker
      to talk to taskcluster queue.
    type:           string
  clientId:
    title:          Client ID
    description: |-
      Taskcluster client id used by taskcluster worker to
      talk to taskcluster queue.
    type:           string
  workerGroup:
    title:          Worker Group
    description: |-
      Typically this would be an aws region - an
      identifier to uniquely identify which pool of
      workers this worker logically belongs to.
    type:           string
  workerId:
    title:          Worker ID
    description: |-
      A name to uniquely identify your worker.
    type:           string
  workerType:
    title:          Worker Type
    description: |-
      This should match a worker_type managed by the
      provisioner you have specified.
    type:           string
  livelogSecret:
    title:          LiveLog Secret
    description: |-
      This should match the secret used by the
      stateless dns server; see
      https://github.com/taskcluster/stateless-dns-server
    type:           string
  publicIP:
    title:          Public IP
    description: |-
      The IP address for clients to be directed to
      for serving live logs; see
      https://github.com/taskcluster/livelog and
      https://github.com/taskcluster/stateless-dns-server
    type:           string
  certificate:
    title:          Certificate
    description: |-
      Taskcluster certificate, when using temporary
      credentials only
    type:           string
  provisionerId:
    title:          Provisioner ID
    description: |-
      The taskcluster provisioner which is taking care
      of provisioning environments with taskcluster worker
      running on them. [default: aws-provisioner-v1]
    type:           string
  refreshURLsPrematurelySecs:
    title:          Refresh URLs Prematurely Secs
    description: |-
      The number of seconds before azure urls expire,
      that the taskcluster worker should refresh them.
      [default: 310]
    type:           integer
  subdomain:
    title:          Subdomain
    description: |-
      Subdomain to use in stateless dns name for live
      logs; see
      https://github.com/taskcluster/stateless-dns-server
      [default: taskcluster-worker.net]
    type:           string
  livelogCertificate:
    title:          LiveLog Certificate
    description: |-
      SSL certificate to be used by livelog for hosting
      logs over https. If not set, http will be used.
    type:           string
  livelogKey:
    title:          LiveLog Key
    description: |-
      SSL key to be used by livelog for hosting logs
      over https. If not set, http will be used.
    type:           string
additionalProperties: false
required:
  - accessToken
  - clientId
  - workerGroup
  - workerId
  - workerType
  - livelogSecret
  - publicIP
