// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package winnative

type (
	// Config applicable to windows native engine
	Config struct {

		// Whether to use PSExec for executing processes
		UsePsExec bool `json:"usePsExec"`
	}
)
