# Configuration file for tc-worker.Dockerfile
transforms:
  - env
config:
  capacity:         1
  credentials:
    # Create a client with the scope:
    # assume:project:taskcluster:worker-test-scopes
    # secrets:get:project/taskcluster/taskcluster-worker/stateless-dns
    clientId:       {$env: TASKCLUSTER_CLIENT_ID}
    accessToken:    {$env: TASKCLUSTER_ACCESS_TOKEN}
  provisionerId:    gecko-t-tc-worker
  workerType:       gecko-test-macosx64
  workerGroup:      macosx-tc-worker
  workerId:         tc-worker-01
  engine:           macosx
  engines:
    macosx:
      createUser: true
      userGroups: ['staff']
  logLevel:         info
  plugins:
    disabled:       ['interactive', 'maxruntime']
    env:
      extra:
        PATH: {$env: PATH}
        TMPDIR: {$env: TMPDIR}
        LANG: {$env: LANG}
        LC_ALL: {$env: LC_ALL}
        TERM: {$env: TERM}
        TERM_PROGRAM: {$env: TERM_PROGRAM}
        SHELL: /bin/bash
  pollingInterval:  10
  reclaimOffset:    120
  temporaryFolder:  /tmp/tc-worker-tmp
  serverIp:           127.0.0.1
  serverPort:         60000
  statelessDNSSecret: fake-secret
  statelessDNSDomain: example.com
  maxLifeCycle:       600
  minimumDiskSpace:   10000000  # 10 GB
  minimumMemory:      1000000   # 1 GB
