// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package volume

import "github.com/taskcluster/taskcluster-worker/runtime"

type (
	// Manager for volumes mounted into task environments
	payload []struct {

		// Path to mount volume into task environment
		MountPoint string `json:"mountPoint"`

		// Identifier for the persisent volume to be reused between tasks.
		Name string `json:"name,omitempty"`

		// Type of volume to request from the engine
		//
		// Possible values:
		//   * "persistent"
		Type string `json:"type"`
	}
)

var payloadSchema = func() runtime.CompositeSchema {
	schema, err := runtime.NewCompositeSchema(
		"volumes",
		`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "addtionalProperies": false,
		  "description": "Manager for volumes mounted into task environments",
		  "items": {
		    "properties": {
		      "mountPoint": {
		        "description": "Path to mount volume into task environment",
		        "title": "Mount Point",
		        "type": "string"
		      },
		      "name": {
		        "description": "Identifier for the persisent volume to be reused between tasks.",
		        "title": "Volume Name",
		        "type": "string"
		      },
		      "type": {
		        "description": "Type of volume to request from the engine",
		        "enum": [
		          "persistent"
		        ],
		        "title": "Volume Type",
		        "type": "string"
		      }
		    },
		    "required": [
		      "type",
		      "mountPoint"
		    ],
		    "type": "object"
		  },
		  "title": "payload",
		  "type": "array"
		}
		`,
		false,
		func() interface{} {
			return &payload{}
		},
	)
	if err != nil {
		panic(err)
	}
	return schema
}()
