// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package osxnative

import "github.com/taskcluster/taskcluster-worker/runtime"

type (
	// Payload for Mac OSX Engine
	payload struct {

		// The first item is the executable to run, followed by command line parameters
		Command []string `json:"command"`

		// Link to an script/executable to run. The file must still be
		// explicitly be referenced by the command field.
		Link string `json:"link,omitempty"`
	}
)

var payloadSchema = func() runtime.CompositeSchema {
	schema, err := runtime.NewCompositeSchema(
		"engine",
		`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "additionalProperties": false,
		  "description": "Payload for Mac OSX Engine",
		  "properties": {
		    "command": {
		      "description": "The first item is the executable to run, followed by command line parameters",
		      "items": {
		        "type": "string"
		      },
		      "minItems": 1,
		      "title": "Command to run",
		      "type": "array"
		    },
		    "link": {
		      "description": "Link to an script/executable to run. The file must still be\nexplicitly be referenced by the command field.",
		      "title": "Executable to download",
		      "type": "string"
		    }
		  },
		  "required": [
		    "command"
		  ],
		  "title": "Payload",
		  "type": "object"
		}
		`,
		true,
		func() interface{} {
			return &payload{}
		},
	)
	if err != nil {
		panic(err)
	}
	return schema
}()
