// This file is AUTO-GENERATED by github.com/taskcluster/taskcluster-worker/codegen/schema-gen - do not edit!

package mockengine

func PayloadSchema() string {
	return "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"additionalProperties\":false,\"properties\":{\"argument\":{\"type\":\"string\"},\"delay\":{\"type\":\"integer\"},\"function\":{\"enum\":[\"true\",\"false\",\"set-volume\",\"get-volume\",\"ping-proxy\",\"write-log\",\"write-error-log\"],\"type\":\"string\"}},\"required\":[\"delay\",\"function\",\"argument\"],\"title\":\"Payload\",\"type\":\"object\"}"
}

func NewPayload() *Payload {
	return new(Payload)
}
